### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_periodic_callbacks'

### ISSUE THREAD

**Issue by camilomarquez** [cryotools/cosipy#22]
Hi all,
We cannot run the Zhadang example from three different computers, with Ubuntu (18.04-18.10) and Manjaro (18.1). Python versions 3.6 and 3.7.4

I attach the error when run COSIPY.py

Any advice is helpful
Thank for your work.
Greetings from Chile

````

 Maximum available time interval from 2009-01-01T00:00 until 2009-12-31T23:00. Time steps: 8760 

Integration from 2009-01-01T06:00 to 2009-01-10T00:00

Checking input data .... 

Temperature data (T2) ... ok 
Please check the input data, its seems they are out of range T2 MAX: 262.77 MIN: 236.27 

Relative humidity data (RH2) ... ok 
Shortwave data (G) ... ok 
Wind velocity data (U2) ... ok 
Precipitation data (RRR) ... ok 
Cloud cover data (N) ... ok 
Pressure data (PRES) ... ok 
Snowfall data (SNOWFALL) ... ok 

 Glacier gridpoints: 16 




Output dataset ... ok
Restart ddataset ... ok 

--------------------------------------------------------------

distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:37895
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:37895
distributed.worker - INFO - Waiting to connect to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.17 GB
distributed.worker - INFO -       Local Directory: /home/marquez/cosipy/dask-worker-space/worker-0tsy4zbr
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:44047
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:44047
distributed.worker - INFO - Waiting to connect to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.17 GB
distributed.worker - INFO -       Local Directory: /home/marquez/cosipy/dask-worker-space/worker-mst64rfw
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:38171
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:38171
distributed.worker - INFO - Waiting to connect to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.17 GB
distributed.worker - INFO -       Local Directory: /home/marquez/cosipy/dask-worker-space/worker-3cthrjcz
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:34015
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:34015
distributed.worker - INFO - Waiting to connect to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    4.17 GB
distributed.worker - INFO -       Local Directory: /home/marquez/cosipy/dask-worker-space/worker-dqdhsk_8
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://127.0.0.1:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
LocalCluster('tcp://127.0.0.1:8786', workers=4, threads=4, memory=16.69 GB)
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:34015
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:44047
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:37895
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:38171
Traceback (most recent call last):
  File "COSIPY.py", line 345, in <module>
    main()
  File "COSIPY.py", line 90, in main
    run_cosipy(cluster, IO, DATA, RESULT, RESTART, futures)
  File "COSIPY.py", line 145, in run_cosipy
    with Client(cluster,processes=False) as client:
  File "/usr/lib/python3.7/site-packages/distributed/client.py", line 647, in __init__
    "Unexpected keyword arguments: {}".format(str(sorted(kwargs)))
ValueError: Unexpected keyword arguments: ['processes']
Exception ignored in: <function Client.__del__ at 0x7f570f363f80>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/distributed/client.py", line 1118, in __del__
  File "/usr/lib/python3.7/site-packages/distributed/client.py", line 1323, in close
AttributeError: 'Client' object has no attribute '_periodic_callbacks'

```

**Comment by AnsArn** [comment]
Hey, could you write me your e-mail. I am going to invite you to slack, where we can work together on the issue. Mine: anselm.arndt@geo.hu-berlin.de
Have you tried the newest version COSIPY (branch: master)?
On my computers (Ubuntu 18.04 and 19.10, Python 3.6 and Python 3.7) I do not have any problem to run the Zhadang example.

**Comment by AnsArn** [comment]
Hey, now I had the same problem. The problem has to do with the version of the dast distributed package. At the moment COSIPY works only with distributed versions smaller than 2.6 (released 15 October 2019).
