### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Sar1hak** [cryotools/cosipy#40]
I am trying to run cosipy using my own NetCDF file but while executing I am getting this error:

**Traceback (most recent call last):       ] | 0% Completed |  0.1s
  File "e:/Code/GITHUB/main/GUI.py", line 1199, in run_Code
    CosipyOutput(date_start= self.StartDate_edit.dateTime().toPyDateTime(),
  File "e:\Code\GITHUB\main\CosipyEvaluation.py", line 338, in CosipyOutput
    run_cosipy(cluster, IO, DATA, RESULT, RESTART, futures)
  File "e:\Code\GITHUB\main\COSIPY.py", line 165, in run_cosipy
    LAYER_IRREDUCIBLE_WATER,LAYER_REFREEZE,stake_names,stat,df_eval = future.result()
  File "C:\Users\Sarthak\anaconda3\envs\dissertation\lib\site-packages\distributed\client.py", line 220, in result
    raise exc.with_traceback(tb)
  File "e:\Code\GITHUB\main\cosipy\cpkernel\cosipy_core.py", line 280, in cosipy_core
    lwc_from_melted_layers = GRID.remove_melt_weq(melt - sublimation - deposition)
  File "e:\Code\GITHUB\main\cosipy\cpkernel\grid.py", line 513, in remove_melt_weq
    SWE = self.get_node_height(idx) * (self.get_node_density(idx)/water_density)
  File "e:\Code\GITHUB\main\cosipy\cpkernel\grid.py", line 705, in get_node_height
    return self.grid[idx].get_layer_height()
IndexError: list index out of range**

**Comment by AnsArn** [comment]
I think some of your glacier gird points are melted away.
Please try to start with a thicker initial glacier height in constants.py (initial_glacier_height).

**Comment by Sar1hak** [comment]
Okay I understand what you mean.
I had another question,  is radiation correction valid for a certain range
of latitude?? because the while calling the radCor.py the length variable
unable to be executed as the value in cos inverse is coming out of the
range of [-1,1]

**Comment by AnsArn** [comment]
Could you tell me the exact line number in the code? And which is your latitude range?

**Comment by Sar1hak** [comment]
Hi Anselm
 Sorry for the late reply, by mistake instead of sending the message I
saved it in the draft.
Below -65 degrees the radCor was showing irregularities.
I have another doubt, I am trying to evaluate using COSIPY for a duration
of 1 hours but I seem to not be going forward after Starting clients and
submitting jobs.
It would really help me if you could tell me what exactly is the
LocalCluster  not able to perform  and would it help if I use SLURMCLuster
(I haven't worked much on SLURM), and also does this imply my inputFile is
corrupt?
PFA Screenshot for the same.

**Comment by AnsArn** [comment]
Ok. Can you tell me the line number in the radCor module?

The LocalCluster is for simulations on your local computer or laptop, the SLURMCluster for high performance computing clusters. 

Can you run the Zhadang example? 
https://cosipy.readthedocs.io/en/latest/Documentation.html

**Comment by Sar1hak** [comment]
radCor.py line 29
