### ISSUE TITLE
Error when running example data

### ISSUE THREAD

**Issue by HenryLikesGlaciers** [cryotools/cosipy#53]
Hi team,

I'm using Cosipy on my windows laptop for a point energy balance of a glacier for my Masters Dissertation but have run into an error in the example data which I suspect is related to a port issue. I believe a similar issue occurs when attempting to run Cosipy on my university institution computers which restrict the port features for security purposes. The console repeats: 

Traceback (most recent call last):
  File "C:\Users\Henry\anaconda3\envs\runCOSIPY\lib\site-packages\distributed\worker.py", line 1200, in get_data
    response = await comm.read(deserializers=serializers)
  File "C:\Users\Henry\anaconda3\envs\runCOSIPY\lib\site-packages\distributed\comm\tcp.py", line 204, in read
    convert_stream_closed_error(self, e)
  File "C:\Users\Henry\anaconda3\envs\runCOSIPY\lib\site-packages\distributed\comm\tcp.py", line 132, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
distributed.core - INFO - Lost connection to 'tcp://127.0.0.1:50399': in <closed TCP>: Stream is closed
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:50371
distributed.nanny - INFO - Worker closed
distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:50374 -> None
Traceback (most recent call last):
  File "C:\Users\Henry\anaconda3\envs\runCOSIPY\lib\site-packages\distributed\comm\tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Any guidance or advice on what the error could be would be hugely appreciated.

**Comment by AnsArn** [comment]
Hey, which version of distributed is installed in your anaconda3 environment? Can you try with a version <=2.5.2 if not already done
