### ISSUE TITLE
Error when running COSIPY

### ISSUE THREAD

**Issue by 00000321** [cryotools/cosipy#55]
I was running the data on my own computer and encountered the following problem when simulating a point of energy mass balance. At first I suspected it was the version of the package that was installed, but after reinstalling, the problem persisted. Here is the error message:

2023-11-18 18:08:51,849 - distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
2023-11-18 18:08:51,852 - distributed.scheduler - INFO - State start
2023-11-18 18:08:51,868 - distributed.scheduler - INFO - Clear task state
2023-11-18 18:08:51,869 - distributed.scheduler - INFO -   Scheduler at:      tcp://127.0.0.1:8786
2023-11-18 18:08:51,869 - distributed.scheduler - INFO -   dashboard at:            127.0.0.1:8787
C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\nanny.py:147: UserWarning: The local_dir keyword has moved to local_directory
  warnings.warn("The local_dir keyword has moved to local_directory")
2023-11-18 18:08:52,023 - distributed.scheduler - INFO - Scheduler closing...
2023-11-18 18:08:52,024 - distributed.scheduler - INFO - Scheduler closing all comms
Traceback (most recent call last):
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\deploy\spec.py", line 262, in __init__
    self.sync(self._correct_state)
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 320, in sync
    return sync(
           ^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 387, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 360, in f
    result = yield future
             ^^^^^^^^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\deploy\spec.py", line 351, in _correct_state_internal
    await asyncio.wait(workers)
  File "E:\Anaconda\Lib\asyncio\tasks.py", line 418, in wait
    return await _wait(fs, timeout, return_when, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\asyncio\tasks.py", line 522, in _wait
    f.add_done_callback(_on_completion)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Nanny' object has no attribute 'add_done_callback'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xie\Desktop\cosipy-master\cosipy-master\COSIPY.py", line 366, in <module>
    main()
  File "C:\Users\xie\Desktop\cosipy-master\cosipy-master\COSIPY.py", line 88, in main
    with LocalCluster(scheduler_port=local_port, n_workers=workers, local_dir='logs/dask-worker-space', threads_per_worker=1, silence_logs=True) as cluster:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\deploy\local.py", line 236, in __init__
    super().__init__(
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\deploy\spec.py", line 264, in __init__
    self.sync(self.close)
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 320, in sync
    return sync(
           ^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 387, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\utils.py", line 360, in f
    result = yield future
             ^^^^^^^^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
            ^^^^^^^^^^^^^^^
  File "C:\Users\xie\AppData\Roaming\Python\Python311\site-packages\distributed\deploy\spec.py", line 421, in _close
    assert w.status in {
           ^^^^^^^^^^^^^
AssertionError: Status.init

Here is the version information of the installation package:
dask _2022.2.0
dask-jobqueue_0.7.3
distributed_2022.2.0

Any advice and help is much appreciated!

**Comment by 00000321** [comment]
The issue has been resolved. The main reason was that the python version was too new.
